import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  HttpStatus,
  Logger,
} from '@nestjs/common';
import type { Request, Response } from 'express';

interface ValidationResponse {
  message?: string | string[];
  error?: string;
  statusCode?: number;
}

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  private readonly logger = new Logger('HttpExceptionFilter');

  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Response>();
    const request = ctx.getRequest<Request>();

    let status = HttpStatus.INTERNAL_SERVER_ERROR;
    let errorCode = 'INTERNAL_SERVER_ERROR';
    let message = 'An unexpected internal error occurred';
    let validationErrors: Array<{ field: string; issue: string }> | undefined;

    if (exception instanceof HttpException) {
      status = exception.getStatus();
      const resBody = exception.getResponse() as string | ValidationResponse;

      // Extract human-readable error code dynamically based on status
      errorCode = this.getErrorCode(status);

      if (typeof resBody === 'string') {
        message = resBody;
      } else if (resBody && typeof resBody === 'object') {
        message =
          resBody.message && Array.isArray(resBody.message)
            ? 'Validation failed'
            : resBody.message || exception.message;

        // Detect and structure validation arrays generated by ValidationPipe
        if (
          status === HttpStatus.BAD_REQUEST &&
          Array.isArray(resBody.message)
        ) {
          errorCode = 'VALIDATION_ERROR';
          validationErrors = resBody.message.map((msg) => {
            const firstSpace = msg.indexOf(' ');
            const field =
              firstSpace !== -1 ? msg.substring(0, firstSpace) : 'unknown';
            return {
              field,
              issue: msg,
            };
          });
        }
      }
    } else if (exception instanceof Error) {
      message = exception.message;
      this.logger.error(
        `Unhandled error caught: ${exception.message}`,
        exception.stack,
      );
    } else {
      this.logger.error(`Unknown exception type caught: ${String(exception)}`);
    }

    const payload = {
      success: false,
      statusCode: status,
      errorCode,
      message,
      ...(validationErrors ? { errors: validationErrors } : {}),
      timestamp: new Date().toISOString(),
      path: request.url,
    };

    response.status(status).json(payload);
  }

  private getErrorCode(status: number): string {
    const errorMap: Record<number, string> = {
      [HttpStatus.BAD_REQUEST]: 'BAD_REQUEST',
      [HttpStatus.UNAUTHORIZED]: 'UNAUTHORIZED',
      [HttpStatus.FORBIDDEN]: 'FORBIDDEN',
      [HttpStatus.NOT_FOUND]: 'RESOURCE_NOT_FOUND',
      [HttpStatus.CONFLICT]: 'RESOURCE_CONFLICT',
      [HttpStatus.UNPROCESSABLE_ENTITY]: 'UNPROCESSABLE_ENTITY',
      [HttpStatus.TOO_MANY_REQUESTS]: 'RATE_LIMIT_EXCEEDED',
    };

    return errorMap[status] || 'INTERNAL_SERVER_ERROR';
  }
}
